import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <div>
            <div className="navbarContainer">
              <Link as={<h1>Gsdf</h1>} href={"/"}>
                <h3>Navbar</h3>
              </Link>
              <nav className="navbar">
                <Link href={"/login"}>Login</Link>
                <Link href={"/register"}>Register</Link>
                <Link href={"/about"}>About</Link>
                <Link href={"/blog"}>Blog</Link>
                <Link href={"/dashboard"}>Dashboard</Link>
              </nav>
            </div>
          </div>
          {children}
          <div>
            <h4>Footer</h4>
          </div>
        </div>
      </body>
    </html>
  );
}
